name: netflix-stack
services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      # Uncomment if your frontend build needs the API URL at build-time:
      # args: [ "VITE_API_URL=https://api.emougio.com" ]
    environment:
      # Or provide runtime envs if your app reads at runtime
      - VITE_API_URL=https://api.emougio.com
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`netflix.emougio.com`)"
      - "traefik.http.services.front.loadbalancer.server.port=80"
    networks: [proxy]
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - NODE_ENV=production
      # add your secrets here via env or .env file (recommended):
      # - MONGO_URL=...
      # - JWT_SECRET=...
      # - PORT=5000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.emougio.com`)"
      - "traefik.http.services.api.loadbalancer.server.port=5000"
    networks: [proxy]
    restart: unless-stopped

networks:
  proxy:
    external: true
