name: netflix-stack
services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      # If your frontend needs API URL at build-time, uncomment:
      # args:
      #   - VITE_API_URL=https://api.emougio.com
    environment:
      - VITE_API_URL=https://api.emougio.com   # runtime (for Vite-style builds)
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`netflix.emougio.com`)"
      - "traefik.http.routers.front.entrypoints=web"
      - "traefik.http.services.front.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    networks: [proxy]
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/"]
      interval: 15s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=5000                # ensure your server uses this
      # Add your secrets via env or .env file:
      # - MONGO_URL=...
      # - JWT_SECRET=...
      # If your app supports HOST, this ensures 0.0.0.0 binding:
      # - HOST=0.0.0.0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.emougio.com`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.services.api.loadbalancer.server.port=5000"
      - "traefik.docker.network=proxy"
    networks: [proxy]
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5000/"]
      interval: 15s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  proxy:
    external: true
